apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-partner-production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-partner
    spec:
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-partner:v9
        name: piggyback-prod-runner-partner
        env:
          - name: JASYPT_ENCRYPTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jasypt-password
                key: password
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-partner
          containerPort: 8085
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8085
status: {}
